"use strict";

const fs = require("fs");
const path = require("path");

const config = require("./build.config");
const buildOrder = require("./build-order");

const startTime = Date.now();

//==================================================
// Console Helpers
//==================================================

function log(message) {
    console.log(`[BUILD] ${message}`);
}

function warn(message) {
    console.warn(`[WARNING] ${message}`);
}

function error(message) {
    console.error(`[ERROR] ${message}`);
    process.exit(1);
}

//==================================================
// Build
//==================================================

try {

    console.log("");
    console.log("========================================");
    console.log(` ${config.pluginName} Builder`);
    console.log("========================================");
    console.log("");

    //--------------------------------------------------
    // Validate Build Order
    //--------------------------------------------------

    log("Checking build order...");

    const duplicateFiles = [];

    for (let i = 0; i < buildOrder.length; i++) {

        if (buildOrder.indexOf(buildOrder[i]) !== i) {
            duplicateFiles.push(buildOrder[i]);
        }

    }

    if (duplicateFiles.length > 0) {

        error(
            "Duplicate file(s) found in build-order.js:\n" +
            duplicateFiles.join("\n")
        );

    }

    //--------------------------------------------------
    // Validate Source Files
    //--------------------------------------------------

    log("Checking source files...");

    for (const file of buildOrder) {

        if (!fs.existsSync(file)) {
            error(`Missing source file: ${file}`);
        }

    }

    //--------------------------------------------------
    // Warn About Unused Files
    //--------------------------------------------------

    function scanDirectory(directory) {

        const entries = fs.readdirSync(directory, { withFileTypes: true });

        for (const entry of entries) {

            const fullPath = path.join(directory, entry.name);

            if (entry.isDirectory()) {

                scanDirectory(fullPath);

            }
            else if (entry.isFile() && entry.name.endsWith(".js")) {

                const normalized = fullPath.replace(/\\/g, "/");

                if (!buildOrder.includes(normalized)) {

                    warn(`${normalized} exists but is not included in build-order.js`);

                }

            }

        }

    }

    scanDirectory(config.sourceDirectory);

    log(`${buildOrder.length} source files found.`);
    log("");

    //--------------------------------------------------
    // Create Output Directory
    //--------------------------------------------------

    const outputDirectory = config.outputDirectory;

    if (!fs.existsSync(outputDirectory)) {

        fs.mkdirSync(outputDirectory, { recursive: true });

        log(`Created output directory: ${outputDirectory}`);

    }

    //--------------------------------------------------
    // Plugin Header
    //--------------------------------------------------

    const buildDate = new Date().toISOString();

    const header = `/*:
 * @target ${config.target}
 * @plugindesc ${config.description}
 * @author ${config.author}
 * @version ${config.version}
 *
 * @command OpenInventory
 * @text Open Inventory
 * @desc Opens the LOGICPULSE Inventory Scene.
 *lik
 *
 * ============================================================================
 * THIS FILE IS AUTO-GENERATED.
 *
 * DO NOT EDIT THIS FILE.
 *
 * Edit the files inside /src instead.
 *
 * Build Date: ${buildDate}
 * ============================================================================
 */

"use strict";

`;

    //--------------------------------------------------
    // Merge Files
    //--------------------------------------------------

    let pluginSource = header;

    for (const file of buildOrder) {

        log(`✓ ${path.basename(file)}`);

        let content = fs.readFileSync(file, "utf8");

        // Remove duplicate "use strict"
        content = content.replace(/^\s*["']use strict["'];?\s*/m, "");

        pluginSource += `
//=============================================================================
// ${path.basename(file)}
//=============================================================================

`;

        pluginSource += content + "\n\n";

    }

    //--------------------------------------------------
    // Write Output
    //--------------------------------------------------

    fs.writeFileSync(config.output, pluginSource, "utf8");

    //--------------------------------------------------
    // Build Summary
    //--------------------------------------------------

    const elapsed = Date.now() - startTime;
    const stats = fs.statSync(config.output);

    console.log("");
    console.log("========================================");

    log("Build Successful");
    log(`Files : ${buildOrder.length}`);
    log(`Size  : ${(stats.size / 1024).toFixed(2)} KB`);
    log(`Time  : ${elapsed} ms`);
    log(`Output: ${config.output}`);

    console.log("========================================");
    console.log("");

}
catch (err) {

    error(err.stack || err.message);

}